### ISSUE TITLE
Le connecteur News2JSON ajoute des espaces autour de certains caractères dans le ‘FromName’

### ISSUE THREAD

**Issue by DuzzAtNemo** [gegeweb/News2JSON#1]
Exemples :
http://news.nemoweb.net/?Jid=56234cdb$0$3856$426a74cc@news.free.fr
http://news.nemoweb.net/?Jid=d8k2niFjopeU1@mid.individual.net
http://news.nemoweb.net/?Jid=k%jVx.146888$6E6.62607@fx38.am4

**Comment by yamo-nntp** [comment]
J'ai résolu mais pas de manière très élégante : MID : d93v04Fk60tU1@mid.test8  (feed seulement sur nemo.*)

As tu d'autres exemples?

**Comment by DuzzAtNemo** [comment]
Pour le moment je n'ai trouvé que ces trois cas : caractères . : et @

**Comment by yamo-nntp** [comment]
et en gros ils étaient encadrés de deux espaces? 
IE " @ " au lieu de "@"?
Je cherche la bonne RFC.

**Comment by DuzzAtNemo** [comment]
Oui, voir les exemples dans l'ouverture du ticket.

**Comment by yamo-nntp** [comment]
Seul celui du milieu est cliquable.

Résultat : http://news2.nemoweb.net/?Jid=d93v04Fk60tU1@mid.test13

**Comment by DuzzAtNemo** [comment]
C'est GitHub qui n'aime pas les $ dans les URL.
Il suffit de les copier/coller dans un "Nouveu sujet" Nemo => Onglet "Aperçu".

**Comment by yamo-nntp** [comment]
Résolu dans la 'non'-version 0.2.0.8
